name: Security-check

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install slither
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer

      - name: Run Slither
        run: |
          slither ./contracts  # Explicitly run slither on the contracts directory
        continue-on-error: true  

      - name: Install Echidna and run fuzz testing in detached mode
        run: |
          docker pull trailofbits/echidna
          docker run -d -v "$PWD":/home --workdir /home trailofbits/echidna echidna-test ./contracts --contract "MyToken" --max-time 60
        continue-on-error: true

      - name: Save Slither Report
        if: failure()  
        run: |
          mkdir -p slither-report
          slither ./contracts --json slither-report/report.json
          echo "Slither report saved at slither-report/report.json"

      - name: Save Echidna Report
        if: failure()  
        run: |
          mkdir -p echidna-report
          docker run -v "$PWD":/home --workdir /home trailofbits/echidna cp echidna-report/* echidna-report/
          echo "Echidna report saved at echidna-report/"
